### PR TITLE
Update Script to fdk-aac 2.0.2

### PR DESCRIPTION
**Pull request by nkh0472**
Please add fdk-aac-2.0.2.tar.gz first!

In setup.sh:
```
...
wget https://github.com/kekyo/fdk-aac-win32-builder/releases/download/distributes/fdk-aac-2.0.2.tar.gz
...
```

### CODE REVIEW

**Comment by kekyo** [comment]
@nkh0472 Thank you updating fdk-aac up to 2.0.2!

I uploaded tar.gz file into GitHub release dists. Could you test it?
And I find more patch files into your repo's master branch. Would you include into this PR?

**Comment by nkh0472** [comment]
By the way, I found the fdkaac 1.0.2 has been released.
I'll test them soon.

**Comment by nkh0472** [comment]
There is some error when running it, I'll try to find why tomorrow.

**Comment by kekyo** [comment]
fdkaac-1.0.2.tar.gz fetched from https://github.com/nu774/fdkaac/releases/tag/v1.0.2 and placed [release tag.](https://github.com/kekyo/fdk-aac-win32-builder/releases/tag/distributes)

**Comment by nkh0472** [comment]
Error happened because lack of fdk-aac-2.0.2/configure :
```
+ cd fdk-aac-2.0.2
+ CC='gcc -pipe -static-libgcc'
+ CXX='g++ -pipe -static-libgcc'
+ ./configure --prefix=/mingw64/x86_64-w64-mingw32/ 'CFLAGS=-O3 -flto -march=native'
./build.sh: line 44: ./configure: No such file or directory
+ make -j8
make: *** No targets specified and no makefile found.  Stop.
+ make install
make: *** No rule to make target 'install'.  Stop.
```
When executing `autoreconf -i` to create ./configure, more errors showed. Then the problem was solved by install libtool by executing 'pacman -S libtool`.

**Comment by nkh0472** [comment]
Now the `build.sh` script could run normally.

However, when run `test.sh`, it looks like there may be three files that are not as expected:
```
$ ./test.sh
[100%] 01:35.852/01:35.852 (66x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.453
[100%] 01:35.852/01:35.852 (54x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.791
[100%] 01:35.852/01:35.852 (53x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.821
[100%] 01:35.852/01:35.852 (86x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.110
[100%] 01:35.852/01:35.852 (53x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.815
[100%] 01:35.852/01:35.852 (64x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.502
[100%] 01:35.852/01:35.852 (76x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.263
[100%] 01:35.852/01:35.852 (63x), ETA 00:00.000
4227066/4227066 samples processed in 00:01.523
references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/BattleThemeA_p29_44_128.pcm differ: char 20507, line 1
references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/BattleThemeA_p2_44_m1.pcm differ: char 20263, line 1
references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/BattleThemeA_p2_44_m5.pcm differ: char 20497, line 1
```
These three files are playable. After a simple audition, I didn't find any abnormality in them. I'll attach them below.
[x86_64-w64-mingw32_test.zip](https://github.com/kekyo/fdk-aac-win32-builder/files/6507921/x86_64-w64-mingw32_test.zip)

 
I'm not sure if this is due to the libfdk-aac update. But I think now that the compiled file is ready to run, it might be ok to commit.

**Comment by kekyo** [comment]
Hmm, interesting (improved and like :)

The reference files were made from non-optimized encoder by [test-materials/make.sh](test-materials/make.sh) .
So, you can update by it with new 2.0.2/1.02 binary with `CFLAGS="-O0"` option.

**Comment by nkh0472** [comment]
> So, you can update by it with new 2.0.2/1.02 binary with `CFLAGS="-O0"` option.

I‘ve tested it, the result was not changed.

More than that, I've tested the ffmpeg-4.4, the result was same as above.

Since 5 of the 8 files tested are the same, I think the software is working properly. This may be caused by changes in libfdk-aac.

According to the signature information at the end of the aac files on both sides, the change should occur between libfdk-aac 4.0.0 and libfdk-aac 4.0.1. The details may be found in the Android git repository……

**Comment by nkh0472** [comment]
By the way, the PCM files generated by software with `CFLAGS="-O0"`/`CFLAGS="-O3 -flto -march=native"` are binary identical;
and the AAC files generated by software with `CFLAGS="-O0"`/`CFLAGS="-O3 -flto -march=native"` differ only at the signature at the end of the file.

**Comment by nkh0472** [comment]
I further tested the 2.0.0 and 2.0.1 versions of fdk-aac, only the test result of version 2.0.1 was the same as the source file you provided. 

<details>
<summary>Logs of compare</summary>

```
+ cmp references/battleThemeA_p2_44_128.pcm artifacts/x86_64-w64-mingw32_test/200battleThemeA_p2_44_128.pcm
references/battleThemeA_p2_44_128.pcm artifacts/x86_64-w64-mingw32_test/200battleThemeA_p2_44_128.pcm differ: char 19807, line 1
+ cmp references/BattleThemeA_p5_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p5_44_128.pcm
references/BattleThemeA_p5_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p5_44_128.pcm differ: char 20931, line 1
+ cmp references/BattleThemeA_p23_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p23_44_128.pcm
references/BattleThemeA_p23_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p23_44_128.pcm differ: char 20569, line 1
+ cmp references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p29_44_128.pcm
references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p29_44_128.pcm differ: char 18819, line 1
+ cmp references/BattleThemeA_p39_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p39_44_128.pcm
references/BattleThemeA_p39_44_128.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p39_44_128.pcm differ: char 20561, line 1
+ cmp references/BattleThemeA_p2_44_256.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_256.pcm
references/BattleThemeA_p2_44_256.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_256.pcm differ: char 20447, line 1
+ cmp references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_m1.pcm
references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_m1.pcm differ: char 20171, line 1
+ cmp references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_m5.pcm
references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/200BattleThemeA_p2_44_m5.pcm differ: char 20299, line 1

+ cmp references/battleThemeA_p2_44_128.pcm artifacts/x86_64-w64-mingw32_test/201battleThemeA_p2_44_128.pcm
+ cmp references/BattleThemeA_p5_44_128.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p5_44_128.pcm
+ cmp references/BattleThemeA_p23_44_128.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p23_44_128.pcm
+ cmp references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p29_44_128.pcm
+ cmp references/BattleThemeA_p39_44_128.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p39_44_128.pcm
+ cmp references/BattleThemeA_p2_44_256.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p2_44_256.pcm
+ cmp references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p2_44_m1.pcm
+ cmp references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/201BattleThemeA_p2_44_m5.pcm

+ cmp references/battleThemeA_p2_44_128.pcm artifacts/x86_64-w64-mingw32_test/202battleThemeA_p2_44_128.pcm
+ cmp references/BattleThemeA_p5_44_128.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p5_44_128.pcm
+ cmp references/BattleThemeA_p23_44_128.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p23_44_128.pcm
+ cmp references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p29_44_128.pcm
references/BattleThemeA_p29_44_128.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p29_44_128.pcm differ: char 20507, line 1
+ cmp references/BattleThemeA_p39_44_128.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p39_44_128.pcm
+ cmp references/BattleThemeA_p2_44_256.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p2_44_256.pcm
+ cmp references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p2_44_m1.pcm
references/BattleThemeA_p2_44_m1.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p2_44_m1.pcm differ: char 20263, line 1
+ cmp references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p2_44_m5.pcm
references/BattleThemeA_p2_44_m5.pcm artifacts/x86_64-w64-mingw32_test/202BattleThemeA_p2_44_m5.pcm differ: char 20497, line 1
```
</details>
So it looks like the reference file you provided was generated by version 2.0.1?
Perhaps such a comparative test itself cannot be carried out across versions...

---
PS: According to the signature information at the end of these AAC files, the corresponding relationship between fdk-aac and libfdk-aac is as follows:

fdk-aac | libfdk-aac
--- | ---
2.0.0 | 4.0.0
2.0.1 | 4.0.0
2.0.2 | 4.0.1

**Comment by nkh0472** [comment]
I guess it is ready to merge……

**Comment by nkh0472** [comment]
Look what I've found!
[443d38963e804ce1133e2338937e1cf389092b52 - platform/external/aac - Git at Google](https://android.googlesource.com/platform/external/aac/+/443d38963e804ce1133e2338937e1cf389092b52%5E%21/#F1)

> Enhance encoder audio quality for vbr (FDKenc v4.0.1).
> 
> Bug: 149489652
> Test: atest android.media.cts.EncoderTest#testAACEncoders
> Change-Id: I4af82bd104a94710d1977eaa0bd086aa743d3adf

> diff --git a/libAACenc/include/aacenc_lib.h b/libAACenc/include/aacenc_lib.h
> ```
> ---------------------------------------------
> - VBR_MODE | Approx. Bitrate in kbps/channel
> -          |     AAC-LC    |  AAC-LD/AC_ELD
> -----------+---------------+-----------------
> -    VBR_1 |    32 -  48   |      32 -  56
> -    VBR_2 |    40 -  56   |      40 -  64
> -    VBR_3 |    48 -  64   |      48 -  72
> -    VBR_4 |    64 -  80   |      64 -  88
> -    VBR_5 |    96 - 120   |     112 - 144
> +-----------------------------------------------
> + VBR_MODE | Approx. Bitrate in kbps for stereo
> +          |     AAC-LC    |      AAC-ELD
> +----------+---------------+--------------------
> +    VBR_1 | 32 (HE-AACv2) |         48
> +    VBR_2 | 72 (HE-AACv1) |         56
> +    VBR_3 |      112      |         72
> +    VBR_4 |      148      |        148
> +    VBR_5 |      228      |        224
>  --------------------------------------------
> ```

This commit could explain the [test result above](https://github.com/kekyo/fdk-aac-win32-builder/pull/5#issuecomment-843970135). The bitrate limit for each variable bitrate mode is changed in libfdk-aac 4.0.1, so as in fdk-aac 2.0.2!

**Comment by kekyo** [comment]
Sorry slower reply and you did great work!

I verified Android aac document and entire your patch (include explained pcm format topic) on my environment and looks good to me.
Would you include any other items? I feel the patch-1 will be merged better before your patch-2.

**Comment by nkh0472** [comment]
I just open a new pull request for my patch-2 branch. Those two PRs are aimed at different contents, so the order of merger is not important.

**Comment by nkh0472** [comment]
I don’t think there will be more changes in this PR.

**Comment by kekyo** [comment]
Merged, thank you!

**Pull request merged**
